version: "3.8"

services:
  node1:
    image: microchain
    container_name: node1
    ports:
      - "5000:5000"
    networks:
      - miniblockchain-network

  node2:
    image: microchain
    container_name: node2
    ports:
      - "5001:5001"
    networks:
      - miniblockchain-network

networks:
  miniblockchain-network:
    driver: bridge
